<h1>About Me</h1>
<div class="about-container">
  <div class="text-container">
    <p class="text-secondary">
      Hello! I’m Lucas, 21, with a passion for software development, gaming (mostly Path of Exile), guitar, and RPGs. I’m currently based in Brazil, where I’ve lived my whole life.
    </p>
    <p class="text-secondary">
      I’ve been working in web development for the past two and a half years, mainly focused on PHP (Zend MVC), JavaScript (React and Next.js), and Python (MVC with Django). Beyond work, I am pursuing a technical course in Systems Analysis and Development at Estácio, expecting to graduate next year (2026). Previously, I studied Computer Science at UNIVEM for three years (2021–2024).
    </p>
    <p class="text-secondary">
      This project is an example of applying my skills and knowledge to something I’m passionate about: games, particularly Path of Exile, a game I’ve invested a lot of time in.
    </p>
    <p class="text-secondary">
      My goal right now is to keep evolving as a person and programmer, and find a place where i can trive and show my skills to the fullest of their cappabilites
    </p>
  </div>
  <div class="image-about-container">
    <img src="/img/characterImg.png" alt="Character">
    <p class="text-secondary">
      Merecenaries character (lvl 91 Raise Spiders Witch)
      - ingame name: godaowow#3469        
    </p>
    <div>
      <p> also i have 3 cats</p>
      <img src="/img/cali.jpg" style="height: 300px" alt="Character">
      <img src="/img/latte.jpg" style="height: 300px" alt="Character">
      <img src="/img/tobias.jpg" style="height: 300px" alt="Character">
    </div>
  </div>
</div>
