<h1>About This Project</h1>
<p>
    This project tracks currency values from Path of Exile (possibly) in real-time using poe.ninja's public API and presents the data through interactive charts. It showcases a full-stack implementation using PHP (Laminas + Doctrine) for the backend, and JavaScript (Chart.js, React/Vanilla JS) for the frontend. 
</p>
<p>
    If you have any previous PoE experiencie you may have noticed the similarities to poe.ninja's main page. Thats totally intentional, my ideia was to grasp this concept in a more GGG style, as if the company had made that page instead of someone else. As a bonus im using poe.ninja's API to fetch currency data when i call the script, so it makes it even more of a "clone".
</p>
<p>
    The application includes historical trends, currency counts, and mini item details, demonstrating practical skills in data fetching, database management, and responsive web design.
</p>
<p>
    I made it as a portfolio/study/fun project and also to learn more about laminas and doctrine since my previous experiencie was with just zend and PHP. The topic (PoE) was choosen to show how to use games as a form to learn web development.
</p>