services:
  app:
    build: .
    container_name: poe-tracker-app
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./bin:/var/www/html/bin
    networks:
      - poe-network

  web:
    image: nginx:stable-alpine
    container_name: poe-tracker-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - poe-network

networks:
  poe-network:
    driver: bridge
